### ISSUE TITLE
Swagger Validation error

### ISSUE THREAD

**Issue by robbiegleeson** [gawhelan/koa-openapi-ui#1]
**Description**
Module throws error for response type of `file`.

**Example specification**

```javascript
/file:
    get:
      summary: Get a file
      responses:
        200:
          description: OK
          schema:
            type: file
```

**Issue**
Swagger.io now supports the use of `file` as a response type.

**Suggested resolution**
Update package `swagger2` used for validation to latest version `0.0.27`

**Comment by gawhelan** [comment]
@robbiegleeson Have you confirmed that `swagger2` `0.0.27` fixes this issue?

**Comment by robbiegleeson** [comment]
@gawhelan Updating the version does **NOT** fix the issue. I'll take a look and complete a PR tonight

**Comment by gawhelan** [comment]
@robbiegleeson This is an upstream problem with `swagger2`. As a workaround you could try something like:

```yaml
/file:
  get:
    produces:
      - application/pdf
    responses:
      200:
        description: Return a PDF file
        schema:
          type: string
          format: binary
```
